keywords: Nerd,Developer,Programming,Ruby,JavaScript
author: Originerd
description: You call it procrastination, I call it thinking.
avatar: https://s.gravatar.com/avatar/9d190117e3e36e388428d35d6291906a?s=128

twitter: Originerds
rss: atom.xml

# Comment
duoshuo:
disqus:
